import 'package:flutter/material.dart';

abstract class AppColors {
  static const Color primaryColor = Color(0xffff6e66);
  static const Color primaryDarkColor = Color(0xffB2322B);
  static const Color secondaryColor = Color(0xffEF675E);
  static const Color deepRedColor = Color(0xffE44C45);
  static const Color lightGrayishRedColor = Color(0xffF9F5F4);
  static const Color dartColor = Color(0xff1F0503);
  static const Color brownRedColor = Color(0xff591613);
  static const Color brownishRedColor = Color(0xff7A1F19);
  static const Color whitSmokeColor = Color(0xffFFF1F0);
  static const Color formBorderColor = Color(0xffFFB6B2);
  static const Color lightRedColor = Color(0xffB4B4B4);
  static const Color spaceGreenColor = Color(0xff64DD17);
  static const Color reportBottomTitleColor = Color(0xffE3E0E0);
  static const Color reportLeftTitleColor = Color(0xffFF928C);
  static const Color softYellowColor = Color(0xffF49C01);
  static const Color greenColor = Color(0xff3FA817);
  static const Color blueColor = Color(0xff116CD1);
  static const Color purpleColor = Color(0xffA21EAE);

  //Product Status Color
  static const Color draftProductStatusColor = Color(0xff76A2E8);
  static const Color pendingProductStatusColor = Color(0xff00B0FF);
  static const Color activeProductStatusColor = Color(0xff64DD17);
  static const Color inactiveProductStatusColor = Color(0xffDFDCDC);
  static const Color expiredProductStatusColor = Color(0xffE44C45);

  static const Color pageBackground = Color(0xFFFAFBFE);
  static const Color productEditPageBackground = Color(0xFFE5E5E5);
  static const Color statusBarColor = Color(0xffee9792);
  static const Color appBarColor = Color(0xffee9792);
  static const Color appBarIconColor = Color(0xFFFFFFFF);
  static const Color appBarTextColor = Color(0xFFFFFFFF);
  static const Color saleVerticalDividerColor = Color(0xffFF4588);
  static const Color orderVerticalDividerColor = Color(0xff76A2E8);
  static const Color yellowColor = Color(0xffFFE800);
  static const Color lightColor = Color(0xffEBEEFA);
  static const Color spaceGrayColor = Color(0xffD5D6DA);
  static const Color lightBlueColor = Color(0xfff3f5ff);
  static const Color lightBlueColor2 = Color(0xffe8ecff);
  static const Color lightBlueColor3 = Color(0xFFCFCBF5);
  static const Color lightBlueColor4 = Color(0xFFF4F6FF);

  static const Color whiteColor = Color(0xFFFFFFFF);
  static const Color secondaryTextColor =  Color(0xFF737373);
  static const Color inputBorderColor =  Color(0xFFEff2FF);
  static const Color spaceBlueColor =  Color(0xff2542BB);
  static const Color spaceWhiteColor =  Color(0xffF4F4F4);
  static const Color orangeColor =  Color(0xffFF7144);
  static const Color whiteGrayColor =  Color(0xffEFEFF0);
  static const Color grayWishColor =  Color(0xffB7B9C3);
  static const Color spaceGrayWishColor =  Color(0xffE7EAFF);
  static const Color blackColor =  Color(0xff29353D);
  static const Color whiteGrayWishColor =  Color(0xffDEDEDE);
  static const Color formFieldBorderColor =  Color(0xffE1E5F7);
  static const Color pureBlackColor = Color(0xff000000);
  static const Color orderCancelColor = Color(0xFFE6465E);
  static const Color orderCancelBGColor = Color(0xFFF7e9e9);
  static const Color orderCancelBGColor2 = Color(0xFFFEF6F6);
  static const List<Color> bottomNavColor = [secondaryColor,primaryColor];

  static const Color titleIndicatorColor = Color(0xFFFF4588);
  static const Color titleTextColor = Color(0xFF1B2724);
  static const Color profileBorderColor = Color(0xFFE5E9EC);
  static const Color wireFrameIconColor = Color(0xFFD4D4D4);
  static const Color dollarColor = Color(0xFF38DE87);
  static const Color wireFrameBGColor = Color(0xFFEFF2FF);
  static const Color ratingColor = Color(0xFFF4BB22);
  static const Color softGreenColor = Color(0xFF38DE87);
  static const Color lightGrayColor = Color(0xFFEDEDED);
  static const Color grayColor = Color(0xFFBBBBBB);
  static const Color textColor = Color(0xFF5F5F5F);
  static const Color softBlueColor = Color(0xFFE7EAFF);
  static const Color lightShadedGrayColor = Color(0xffFAFAFA);
  static const Color lightShadedGrayColor2 = Color(0xff999999);
  static const Color shadedGrayWishColor = Color(0xff9C9C9C);
  static const Color ghostWhiteColor = Color(0xffF7F7FD);
  static const Color lineChartColor = Color(0xff5157E0);
  static const Color darkColor = Color(0xff383535);
  static const Color dividerColor = Color(0xffECEEF1);
  static const Color fabBtnColor = Color(0xFF38DE87);
  static const Color deleteBtnBgColor = Color(0xFFEDF0F7);
  static const Color validTextColor = Color(0xFFA5A5A5);
  static const Color shadowColor = Color(0xFF18274B);
  static const Color unselectedLabelColor = Color(0xFF9C9C9C);
  static const Color tabBarColor = Color(0xFFEFF1FF);
  static const Color deleteChipColor = Color(0xFF828282);
  static const Color pendingPromotionColor = Color(0xFFFFA048);
  static const Color inactivePromotionColor = Color(0xFFEF4136);
  static const Color activePromotionColor = Color(0xff129021);
  static const Color dateIconColor = Color(0xff999999);
  static const Color proItemQualityColor = Color(0xffeef0fb);
  static const Color cardBorderColor = Color(0xfff2f5ff);
  static const Color cardShadowColor = Color(0xffa3a3a3);
  static const Color expirePromotionColor = Color(0xfff7e9e9);
  static const Color textExpirePromotionColor = Color(0xffff5454);
  static const Color textValidDatePromotionColor = Color(0xffe45c5c);
  static const Color unselectedStarColor = Color(0xffBDC2D9);
  static const Color chatActiveColor = Color(0xff0ee171);
  static const Color darkGrayColor = Color(0xff5F676E);
  static const Color deepOrangeColor = Color(0xffFD7043);

}
